### ISSUE TITLE
Install failed on Big Sur

### ISSUE THREAD

**Issue by boblund** [Winterreisender/webview-nodejs#10]
This command failed: sh -c node-gyp-build when trying to build (arch === arm64). I did a prior successful npm i node-gyp. Any hints?

**Comment by Winterreisender** [comment]
This may be related to `ffi-napi`, our dependency, which has issues on macos arm64.

One of the related issues: https://github.com/node-ffi-napi/node-ffi-napi/issues/243

**Comment by Winterreisender** [comment]
One alternative to `ffi-napi` is [sbffi](https://github.com/bengl/sbffi), whose last release is in 2020, same as `ffi-napi`, but began to commit codes recently. We'll consider migratng to [sbffi](https://github.com/bengl/sbffi) if the release a new updated version.

Node.js also has a pull request `#46905` which aims to provide a built-in `node:ffi` module like deno. We'll focus on that.

**Comment by boblund** [comment]
I tried doing the install with arch === i386 and get the same error, although the error output is somewhat different.

**Comment by Winterreisender** [comment]
We tried to migrate to koffi to solve this problem, it passed the GitHub Acton's macOS test.  
Because I do not have any macOS devices, I'm not sure if it really works , you can try the new verson by:
```bash
npm i webview-nodejs@0.2.3
```

**Comment by Winterreisender** [comment]
More than 3 months passed since the latest reply, this issue will be closed. If anyone have similar problems, please open a new issue.
