### ISSUE TITLE
how to set postion of the window?

### ISSUE THREAD

**Issue by anhnhoktvn** [Winterreisender/webview-nodejs#15]
Is there a way to change the position of the window. For example, I'd like to make it in the center of the screen. Thank you!

**Comment by Winterreisender** [comment]
Thanks for your feedback. But unfortunately our upstream project, [webview](https://github.com/webview/webview), does not support this feature, so we can't do that. This repo is only a Node.js binding for [webview](https://github.com/webview/webview). If you need new features, you could send you feedback to [webview](https://github.com/webview/webview). I would be happy to try making API bindings after [webview](https://github.com/webview/webview) adding them.

**Comment by Winterreisender** [comment]
You may see this feature request in  [webview](https://github.com/webview/webview): https://github.com/webview/webview/issues/642, in which it mentioned a method to center the window using C++, [webview-nodejs](https://github.com/Winterreisender/webview-nodejs) support setting the target window handle. So if you can create a centered window, and pass the handle to webview-nodejs by using `target` parameter in `new Webview(debug?: boolean, libPath?: string, target?: null)`, it may work.
