### ISSUE TITLE
terminate window cause node to stop

### ISSUE THREAD

**Issue by BilalBoulifa** [Winterreisender/webview-nodejs#16]
hello guys,

in my code, I need to open a window, do some processing then terminate it then continue doing some processing.
but once I terminate the window the whole node code stop suddenly without any error, nothing is getting executed after window termination.

**Comment by BilalBoulifa** [comment]
resolved by moving the whole WebView related code in a separate worker.

**Comment by Winterreisender** [comment]
Thanks for your feedback, this will be documented.
