### ISSUE TITLE
Some examples stopped working (for me)

### ISSUE THREAD

**Issue by dirkk0** [Winterreisender/webview-nodejs#17]
Hi,

  I revisited this project and realized that something is not working for me in the latest version 0.2.4.
When I start a new project with `npm install webview-nodejs`  not everything seems to be installed.

Downgrading to 0.1.3 makes the examples work again. According to my tests, just the trivial hello world example works, the more sophisticated ones (which use `bind` like [this one at the bottom](https://github.com/Winterreisender/webview-nodejs/wiki/Tutorial)) do not work for me.

I am on node 19.9.

Thanks,
  Dirk

**Comment by Winterreisender** [comment]
Thanks，I'll try to solve this.

**Comment by Winterreisender** [comment]
currently let user install 0.1.3 in readme, And I'll consider which ffi to use later

**Comment by Winterreisender** [comment]
I finally got some time, and found this is a reproducible bug in Linux (and maybe macOS, but I don't have a macOS device to check it). Further works will be done later.

**Comment by Winterreisender** [comment]
Sorry, I can't fix it quickly. The conslusion is that, with koffi, calling `webkit_web_view_evaluate_javascript` or `webkit_web_view_run_javascript` will make the window crash. May be I should use another ffi.
This is what I tried:
1. Use koffi's async call
2. Use older version of libwebview.so
3. Use newer version of libwebview.so
4. Check if the `js` if freed before execute.
5. Change deprecated `webkit_web_view_run_javascript` to `webkit_web_view_evaluate_javascript` and recompile

**Comment by Winterreisender** [comment]
I'll have some spare time in Friday this week, and I decided to keep developing version 0.1 instead of 0.2, the 0.1 version will be v0.3 in the next release.

**Comment by Winterreisender** [comment]
This is temporarily fixed by rolling back to v0.1 in v0.3. I'll try new FFI method in the feature.

**Comment by Winterreisender** [comment]
This is fixed in v0.4.0 with SWING and NAPI.
