### ISSUE TITLE
Add to readme: how to install CMake on Windows.

### ISSUE THREAD

**Issue by nycki93** [Winterreisender/webview-nodejs#19]
When installing v0.4.0 on Windows 10, I got the error 'OMG CMake is not installed. Install CMake.'

I was able to solve this by running `winget install Kitware.CMake`. I also had to close and re-open my console to get the path to update.

Just putting this here in case anyone else gets stuck. Would be good to add this info to the readme.

**Comment by Winterreisender** [comment]
Thanks! I'll do it later.

**Comment by Winterreisender** [comment]
The document of this repo really needs a rewriting. If v0.4.0 is proven stable and I have enough time, the next step is totally update the document.
