### ISSUE TITLE
Deprecation notice libwebview-nodejs/src/webview.h

### ISSUE THREAD

**Issue by wipmate** [Winterreisender/webview-nodejs#25]
During build, there is a deprecation notice about the function call `webkit_web_view_run_javascript()` in [webview.h:689](https://github.com/Winterreisender/webview-nodejs/blob/5cfb37afd8e6a5ea5c4b083be3b9f83007aaad52/libwebview-nodejs/src/webview.h#L689).

The warning says: `warning: 'void webkit_web_view_run_javascript(WebKitWebView*, const gchar*, GCancellable*, GAsyncReadyCallback, gpointer)' is deprecated: Use 'webkit_web_view_evaluate_javascript' instead [-Wdeprecated-declarations]`

As of now, this warning doesn't cause any issues, but it may be worth being aware of.

Environment: Debian 12 with libwebkit2gtk-4.0-dev

**Comment by Winterreisender** [comment]
Yes, this is a issue of github.com/webview/webview, our upstream project. Hope it will be fixed soon.
