### ISSUE TITLE
libwebkit2gtk-4.0 not available in Ubuntu 24 & Debian 13

### ISSUE THREAD

**Issue by ckir** [Winterreisender/webview-nodejs#27]
Since libwebkit2gtk-4.0 is not available in Ubuntu 24 & Debian 13 (moved to  libwebkit2gtk-4.1) I'm leaving this here as a possible solution for Ubuntu.

The solution is as follows:

1.- Update the sources file (sudo vim /etc/apt/sources.list.d/ubuntu.sources) and add the following lines:

Types: deb
URIs: http://br.archive.ubuntu.com/ubuntu/
Suites: jammy noble-updates noble-backports
Components: main restricted universe multiverse
Signed-By: /usr/share/keyrings/ubuntu-archive-keyring.gpg

Types: deb
URIs: http://security.ubuntu.com/ubuntu/
Suites: jammy-security
Components: main restricted universe multiverse
Signed-By: /usr/share/keyrings/ubuntu-archive-keyring.gpg

2.- Execute sudo apt update
3.-Execute sudo apt install libwebkit2gtk-4.0-dev

After that, your installation should go smoothly.

P.S. After install you can edit /etc/apt/sources.list.d/ubuntu.sources and remove the above lines

**Comment by Winterreisender** [comment]
You may also check webview/webview#1110 , we'll follow the upstream's solutions

**Comment by Winterreisender** [comment]
Upstream project (https://github.com/webview/webview) suggests use `libwebkit2gtk-4.1-dev` for Ubuntu 24.04, you may have a try

**Comment by Winterreisender** [comment]
Upstream project now have a detailed guide for Ubuntu 24 and Debian 13. Since we just added a link to that, there's no need to change the README.
