### ISSUE TITLE
Documentation with broken links

### ISSUE THREAD

**Issue by kitingChris** [Winterreisender/webview-nodejs#9]
For example the Link to "Examples" is no longer valid. 
Would be great if you could update the documentation.

**Comment by Winterreisender** [comment]
This is confirmed:

Click Documentation (Github Page) and then click Examples wont work.
But clicking these links in GitHub Repo Page directly is OK.

**Comment by Winterreisender** [comment]
This should be fixed after using absolute URL. 
In addition the `Documentation` is renamed to `API Reference` since it's generated by TypeDoc automaticlly.
